### ISSUE TITLE
Updates for 2016.3.2

### ISSUE THREAD

**Issue by garyng** [matthewvukomanovic/Vukomanovic.Resharper#1]
Any updates for 2016.3.2? 
Thanks! 😄

**Comment by matthewvukomanovic** [comment]
I don't have time to update it to the latest version at the moment (especially since I haven't updated resharper yet).

However if you want to clone it and do a pull request I would be happy to pull that in and update it.

**Comment by matthewvukomanovic** [comment]
I have pushed up a version now which builds all the versions from 2016.1 up to 2017.1

I've also uploaded the extension versions to the resharper nuget server

**Comment by garyng** [comment]
Wow! Awesome!
Thanks! 💯
